# Site settings
title: 浮云
email: 
description: > # this means to ignore newlines until "baseurl:"
  一条咸鱼
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cloudli.top" # the base hostname & protocol for your site
twitter_username: username
github_username: imcloudfloating

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]